text = """
I AIN’T SORRY
I AIN’T SORRY
I AIN’T SORRY
N---- NAH
I AIN’T SORRY
I AIN’T SORRY
I AIN’T SORRY

HE TRYING TO ROLL ME UP (I AIN’T SORRY)
I AIN’T PICKING UP (I AIN’T SORRY)
HEADED TO THE CLUB (I AIN’T SORRY)
I AIN’T THINKING ‘BOUT YOU (I AIN’T SORRY)

ME AND MY LADIES SIP MY D'USSÉ CUPS
I DON’T GIVE A F--- CHUCKING MY DEUCES UP
SUCK ON MY BALLS PAUSE
I HAD ENOUGH
I AIN’T THINKING 'BOUT YOU
I AIN’T THINKING 'BOUT

MIDDLE FINGERS UP
PUT THEM HANDS HIGH
WAVE IT IN HIS FACE 
TELL ‘EM BOY BYE
TELL ‘EM BOY BYE
BOY BYE
MIDDLE FINGERS UP 
I AIN’T THINKING 'BOUT YOU

I AIN’T SORRY 
I AIN’T SORRY
I AIN’T SORRY
N---- NAH
I AIN’T SORRY 
I AIN’T SORRY
I AIN’T SORRY
NO NO HELL NAH

NOW YOU WANT TO SAY YOU’RE SORRY 
NOW YOU WANT TO CALL ME CRYING
NOW YOU GOTTA SEE ME WILDIN'
NOW I’M THE ONE THAT’S LYING
AND I DON’T FEEL BAD ABOUT IT
IT’S EXACTLY WHAT YOU GET
STOP INDIRECTING MY GRINDING

I AIN’T THINKING BOUT YOU
I AIN’T THINKING BOUT YOU
I AIN’T THINKING BOUT YOU
I AIN’T THINKING BOUT YOU
I AIN’T THINKING BOUT YOU 

MIDDLE FINGERS UP
PUT THEM HANDS HIGH
WAVE IT IN HIS FACE 
TELL ‘EM BOY BYE
TELL ‘EM BOY BYE
BOY BYE
MIDDLE FINGERS UP 
I AIN’T THINKING BOUT YOU

I AIN’T SORRY
I AIN’T SORRY
I AIN’T SORRY
N---- NAH
I AIN’T SORRY 
I AIN’T SORRY
I AIN’T SORRY
NO NO HELL NAH

LOOKING AT MY WATCH HE SHOULD’VE BEEN HOME
TODAY I REGRET THE NIGHT I PUT THAT RING ON
HE ALWAYS GOT THEM FUCKING EXCUSES
I PRAY TO THE LORD YOU REVEAL WHAT HIS TRUTH IS

I LEFT A NOTE IN THE HALLWAY
BY THE TIME YOU READ IT I’LL BE FAR AWAY
I'M FAR AWAY
BUT I AIN’T FUCKING WITH NOBODY
LET’S HAVE A TOAST TO THE GOOD LIFE
SUICIDE BEFORE YOU SEE THIS TEAR FALL DOWN MY EYES
ME AND MY BABY WE GONE BE ALRIGHT
WE GON' LIVE A GOOD LIFE
BIG HOMIE BETTER GROW UP
ME AND MY WHOADIES 'BOUT TO STROLL UP
I SEE THEM BOPPERS IN THE CORNER 
THEY SNEAKING OUT THE BACK DOOR
HE ONLY WANT ME WHEN I’M NOT THERE
HE BETTER CALL BECKY WITH THE GOOD HAIR
HE BETTER CALL BECKY WITH THE GOOD HAIR
"""
print(len(text.split()))

word_count = {}

for word in text.split():
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print(word_count)